"""empty message

Revision ID: 6257766a1bae
Revises: 97f2ad5269bb
Create Date: 2023-09-10 04:21:39.728239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6257766a1bae'
down_revision = '97f2ad5269bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('id_technical',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('id_technical',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
