"""empty message

Revision ID: 97f2ad5269bb
Revises: 
Create Date: 2023-09-01 00:49:33.312894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f2ad5269bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('role', sa.Enum('admin', 'technical', name='role'), nullable=False),
    sa.Column('question_security', sa.Enum('pet', 'color', 'movie', 'food', name='questions'), nullable=False),
    sa.Column('answer_security', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('laptop', 'cpu', 'monitor', 'printer', 'ups', name='type'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('recieve', 'review', 'repair_in_progress', 'cancel', 'finish', name='status'), nullable=False),
    sa.Column('issues', sa.String(length=500), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('id_technical', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_technical'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('user')
    op.drop_table('client')
    # ### end Alembic commands ###
